config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  get "error/index"

  match 'cause_server_side_exception' => 'home#cause_server_side_exception'
  match 'cause_another_exception' => 'home#cause_another_exception'
  match 'cause_critical' => 'home#cause_critical'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  def index
    a = b
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def cause_server_side_exception
    uh_oh = this_variable_has_not_been_set
  end

  def cause_another_exception
    x = nil
    x[:foo]
  end

  def cause_critical
    result = Rollbar.critical("Hull breach!", :shield_level => "#{Random.rand(25)} percent")
    if result.is_a?(Hash)
      puts "it's a hash"
      @uuid = result[:uuid]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      Rollbar.info("User updated.", :user => @user)

      redirect_to users_path, :notice => "User updated."
    else
      Rollbar.warning("Unable to update user.", :user => @user)

      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/cause_critical.html.erb
<h1>Critical Error!</h1>

<% if @uuid %>
<p>Want to your users to be able to reference this issue when they contact support? Give them this token: <%= @uuid %></p>

<p>This URL leads to this occurrence in Rollbar: <a href="https://rollbar.com/instance/uuid?uuid=<%= @uuid %>">https://rollbar.com/instance/uuid?uuid=<%= @uuid %></a></p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to the Rollbar Demo App</h1>

<p>Errors that happen here get reported back to the <a href="https://rollbar.com/demo" target="_blank">Rollbar Demo Project</a>. Click around here with the demo project open in another window or tab and watch the data appear.</p>

<h3>Server-side (Rails)</h3>

<p><%= link_to 'This link causes a server-side exception', '/cause_server_side_exception' %></p>
<p><%= link_to 'This link causes a different exception', '/cause_another_exception' %></p>
<p><%= link_to 'This link causes a critical error', '/cause_critical' %></p>
<p><%= link_to 'This link will 404', '/cause_404' %></p>

<h3>Client-side (Javascript)</h3>

<h4>Uncaught errors</h4>

<p><button class="btn" onclick="nonexistent_function();">Cause an uncaught error</button> (will be reported by window.onerror)</p>

<script>
  function report_message(level) {
    var body = $('#js-log-input').prop('value');
    var data = {
      an_array: [1,2,3],
      an_object: {hello: 'world'},
      a_string: "Hola",
      a_number: 42
    }

    Rollbar.scope({level: level}).log(body, data, function(err) {
      if (err) {
        alert("Got an error reporting to Rollbar: ", err);
      } else {
        alert("Success. Go check the Rollbar project Items page.");
      }
    })
  }
</script>

<h4>Log a message</h4>
<ol>
<li>Enter message text: <input type="text" value="some log message" id="js-log-input" class="span3">
<li>Now press one of these buttons:
<div class="btn-group">
  <button class="btn" onclick="report_message('debug');">Debug</button>
  <button class="btn" onclick="report_message('info');">Info</button>
  <button class="btn" onclick="report_message('warning');">Warning</button>
  <button class="btn" onclick="report_message('error');">Error</button>
  <button class="btn" onclick="report_message('critical');">Critical</button>
</div>
</li>
</ol>

<hr>

<p><b>Note:</b> while this demo is just Rails and Javascript, Rollbar also supports Python, PHP, Node.js, Flash, and anything else that can speak JSON and HTTP to our API.</p>

<h4>Credits</h4>

<p>This simple app is based on the <a target="_blank" href="https://github.com/RailsApps/rails3-bootstrap-devise-cancan">rails3-bootstrap-device-cancan</a> tutorial app.</p>

<h4>Source</h4>

<p>Source code of this app is available on Github at <a href="https://github.com/rollbar/rollbar-rails-demo">https://github.com/rollbar/rollbar-rails-demo</a>. Want to see all the changes we made to the tutorial app? <a href="https://github.com/rollbar/rollbar-rails-demo/compare/d8dee452284d2296b7936a44f78c238704699d04...master">Here's the diff.</a></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Rollbar Rails Demo", root_path, :class => 'brand' %>
<ul class="nav">
  <li>
    <a target="_blank" href="https://rollbar.com/demo/">Open Rollbar Demo Project</a>
  </li>
</ul>
<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>